namespace igLibrary.Gfx
{
	public enum IG_GFX_STENCIL_FUNCTION : uint
	{
		IG_GFX_STENCIL_FUNCTION_NEVER,
		IG_GFX_STENCIL_FUNCTION_LESS,
		IG_GFX_STENCIL_FUNCTION_EQUAL,
		IG_GFX_STENCIL_FUNCTION_LEQUAL,
		IG_GFX_STENCIL_FUNCTION_GREATER,
		IG_GFX_STENCIL_FUNCTION_NOTEQUAL,
		IG_GFX_STENCIL_FUNCTION_GEQUAL,
		IG_GFX_STENCIL_FUNCTION_ALWAYS,
	}
}