namespace igLibrary.Graphics
{
	public static class igGraphics
	{
		public static igCommandSetPrimitiveTypeParametersMetaField SetPrimitiveTypeParamsField = new igCommandSetPrimitiveTypeParametersMetaField();
		public static igCommandSetVertexBufferParametersMetaField SetVertexBufferParamsField = new igCommandSetVertexBufferParametersMetaField();
		public static igCommandSetIndexBufferParametersMetaField SetIndexBufferParamsField = new igCommandSetIndexBufferParametersMetaField();
		public static igCommandSetVertexShaderParametersMetaField SetVertexShaderParamsField = new igCommandSetVertexShaderParametersMetaField();
		public static igCommandSetVertexShaderVariantParametersMetaField SetVertexShaderVariantParamsField = new igCommandSetVertexShaderVariantParametersMetaField();
		public static igCommandSetVertexShaderTextureParametersMetaField SetVertexShaderTextureParamsField = new igCommandSetVertexShaderTextureParametersMetaField();
		public static igCommandSetVertexShaderSamplerParametersMetaField SetVertexShaderSamplerParamsField = new igCommandSetVertexShaderSamplerParametersMetaField();
		public static igCommandSetViewportParametersMetaField SetViewportParamsField = new igCommandSetViewportParametersMetaField();
		public static igCommandSetScissorParametersMetaField SetScissorParamsField = new igCommandSetScissorParametersMetaField();
		public static igCommandSetScissorEnabledParametersMetaField SetScissorEnabledParamsField = new igCommandSetScissorEnabledParametersMetaField();
		public static igCommandSetRasterizeStateBundleParametersMetaField SetRasterizeStateBundleParamsField = new igCommandSetRasterizeStateBundleParametersMetaField();
		public static igCommandSetPixelShaderParametersMetaField SetPixelShaderParamsField = new igCommandSetPixelShaderParametersMetaField();
		public static igCommandSetPixelShaderVariantParametersMetaField SetPixelShaderVariantParamsField = new igCommandSetPixelShaderVariantParametersMetaField();
		public static igCommandSetPixelShaderTextureParametersMetaField SetPixelShaderTextureParamsField = new igCommandSetPixelShaderTextureParametersMetaField();
		public static igCommandSetPixelShaderSamplerParametersMetaField SetPixelShaderSamplerParamsField = new igCommandSetPixelShaderSamplerParametersMetaField();
		public static igCommandSetAlphaTestStateBundleParametersMetaField SetAlphaTestStateBundleParamsField = new igCommandSetAlphaTestStateBundleParametersMetaField();
		public static igCommandSetBlendStateBundleParametersMetaField SetBlendStateBundleParamsField = new igCommandSetBlendStateBundleParametersMetaField();
		public static igCommandSetDepthStateBundleParametersMetaField SetDepthStateBundleParamsField = new igCommandSetDepthStateBundleParametersMetaField();
		public static igCommandSetStencilStateBundleParametersMetaField SetStencilStateBundleParamsField = new igCommandSetStencilStateBundleParametersMetaField();
		public static igCommandSetStencilRefParametersMetaField SetStencilRefParamsField = new igCommandSetStencilRefParametersMetaField();
		public static igCommandSetRenderTargetsParametersMetaField SetRenderTargetsParamsField = new igCommandSetRenderTargetsParametersMetaField();
		public static igCommandSetRenderTargetMaskParametersMetaField SetRenderTargetMaskParamsField = new igCommandSetRenderTargetMaskParametersMetaField();
		public static igCommandXenonSetHiStencilParametersMetaField XenonSetHiStencilParamsField = new igCommandXenonSetHiStencilParametersMetaField();
		public static igCommandXenonSetFlushHiZStencilParametersMetaField XenonSetFlushHiZStencilParamsField = new igCommandXenonSetFlushHiZStencilParametersMetaField();
		public static igCommandXenonGprCountsParametersMetaField XenonGprCountsParamsField = new igCommandXenonGprCountsParametersMetaField();
		public static igCommandPS3SetSCullParametersMetaField PS3SetSCullParamsField = new igCommandPS3SetSCullParametersMetaField();
		public static igCommandSetConstantBoolParametersMetaField SetConstantBoolParamsField = new igCommandSetConstantBoolParametersMetaField();
		public static igCommandSetConstantIntParametersMetaField SetConstantIntParamsField = new igCommandSetConstantIntParametersMetaField();
		public static igCommandSetConstantFloatParametersMetaField SetConstantFloatParamsField = new igCommandSetConstantFloatParametersMetaField();
		public static igCommandSetConstantVec4fParametersMetaField SetConstantVec4fParamsField = new igCommandSetConstantVec4fParametersMetaField();
		public static igCommandSetConstantMatrix44fParametersMetaField SetConstantMatrix44fParamsField = new igCommandSetConstantMatrix44fParametersMetaField();
		public static igCommandSetConstantArrayIntParametersMetaField SetConstantArrayIntParamsField = new igCommandSetConstantArrayIntParametersMetaField();
		public static igCommandSetConstantArrayFloatParametersMetaField SetConstantArrayFloatParamsField = new igCommandSetConstantArrayFloatParametersMetaField();
		public static igCommandSetConstantArrayVec4fParametersMetaField SetConstantArrayVec4fParamsField = new igCommandSetConstantArrayVec4fParametersMetaField();
		public static igCommandSetConstantArrayMatrix44fParametersMetaField SetConstantArrayMatrix44fParamsField = new igCommandSetConstantArrayMatrix44fParametersMetaField();
		public static igCommandApplyConstantBundleParametersMetaField ApplyConstantBundleParamsField = new igCommandApplyConstantBundleParametersMetaField();
		public static igCommandApplyConstantValueListParametersMetaField ApplyConstantValueListParamsField = new igCommandApplyConstantValueListParametersMetaField();
		public static igCommandSetPixelShaderTextureEnabledConstantParametersMetaField SetPixelShaderTextureEnabledConstantParamsField = new igCommandSetPixelShaderTextureEnabledConstantParametersMetaField();
		public static igCommandSetVertexShaderTextureEnabledConstantParametersMetaField SetVertexShaderTextureEnabledConstantParamsField = new igCommandSetVertexShaderTextureEnabledConstantParametersMetaField();
		public static igCommandSetPixelShaderTextureSizeConstantParametersMetaField SetPixelShaderTextureSizeConstantParamsField = new igCommandSetPixelShaderTextureSizeConstantParametersMetaField();
		public static igCommandSetVertexShaderTextureSizeConstantParametersMetaField SetVertexShaderTextureSizeConstantParamsField = new igCommandSetVertexShaderTextureSizeConstantParametersMetaField();
		public static igCommandClearRenderTargetParametersMetaField ClearRenderTargetParamsField = new igCommandClearRenderTargetParametersMetaField();
		public static igCommandDrawPrimitivesParametersMetaField DrawPrimitivesParamsField = new igCommandDrawPrimitivesParametersMetaField();
		public static igCommandDecodeMemoryCommandStreamParametersMetaField DecodeMemoryCommandStreamParamsField = new igCommandDecodeMemoryCommandStreamParametersMetaField();
		public static igCommandCopyTextureParametersMetaField CopyTextureParamsField = new igCommandCopyTextureParametersMetaField();
		public static igCommandUpdateTextureParametersMetaField UpdateTextureParamsField = new igCommandUpdateTextureParametersMetaField();
		public static igCommandExecuteCallbackParametersMetaField ExecuteCallbackParamsField = new igCommandExecuteCallbackParametersMetaField();
		public static igCommandSetCameraMatricesParametersMetaField SetCameraMatricesParamsField = new igCommandSetCameraMatricesParametersMetaField();
		public static igCommandComputeAndSetInstanceMatricesParametersMetaField ComputeAndSetInstanceMatricesParamsField = new igCommandComputeAndSetInstanceMatricesParametersMetaField();
		public static igCommandComputeAndSetInstanceConstantsParametersMetaField ComputeAndSetInstanceConstantsParamsField = new igCommandComputeAndSetInstanceConstantsParametersMetaField();
		public static igCommandSetCommonRenderStateParametersMetaField SetCommonRenderStateParamsField = new igCommandSetCommonRenderStateParametersMetaField();
		public static igCommandSetDitherStateParametersMetaField SetDitherStateParamsField = new igCommandSetDitherStateParametersMetaField();
		public static igCommandBeginNamedEventParametersMetaField BeginNamedEventParamsField = new igCommandBeginNamedEventParametersMetaField();
		public static igCommandEndNamedEventParametersMetaField EndNamedEventParamsField = new igCommandEndNamedEventParametersMetaField();
		public static igCommandIssueBufferedGpuTimestampParametersMetaField IssueBufferedGpuTimestampParamsField = new igCommandIssueBufferedGpuTimestampParametersMetaField();
	}
}